import { test, expect } from '@playwright/test';
test('client can complete a valuation request and revise earlier details', async ({ page }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'Order a valuation', exact: true }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your contact details' })).toBeVisible();
  await page.getByLabel('First name').fill('Alex');
  await page.getByLabel('Last name').fill('Silva');
  await page.getByLabel('Mobile', { exact: false }).fill('0400000000');
  await page.getByLabel('Email', { exact: false }).fill('alex@example.com');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('Street address').fill('12 Sample Street');
  await page.getByLabel('Suburb').fill('Sydney');
  await page.getByLabel('Postcode').fill('2000');
  await page.getByLabel('Preferred valuation date').fill('2026-10-01');
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await expect(page.getByLabel('First name')).toHaveValue('Alex');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByLabel('Street address')).toHaveValue('12 Sample Street');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByText('12 Sample Street, Sydney 2000')).toBeVisible();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Complete sample request' }).click();
  await expect(page.getByRole('heading', { name: 'All set, Alex.' })).toBeVisible();
});
test('mobile navigation, quote form and layout', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('h1')).toContainText('Know its worth');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'reference/mobile-preview.png', fullPage: true });
  await page.getByRole('button', { name: 'Toggle navigation' }).click();
  await page.getByRole('button', { name: 'Property valuations', exact: true }).click();
  await page.getByRole('link', { name: 'Market Assessment', exact: true }).click();
  await page.getByLabel('First name').fill('Alex');
  await page.getByLabel('Last name').fill('Silva');
  await page.getByLabel('Email').fill('alex@example.com');
  await page.getByLabel('Property address').fill('12 Sample Street');
  await page.getByRole('button', { name: 'Get my free quote' }).click();
  await expect(page.getByRole('status')).toContainText('Your sample request is ready');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('desktop landing page loads without errors', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.locator('.hero-image').evaluate(img => img.decode());
  await page.screenshot({ path: 'reference/desktop-preview.png', fullPage: true });
  expect(errors).toEqual([]);
});
