import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{
 await page.route('**/api/form-config',route=>route.fulfill({json:{available:true,siteKey:null,attachmentsEnabled:true}}));
 await page.route('**/api/enquiries',route=>route.fulfill({json:{ok:true}}));
});

test('valuation and quote validate contact details and accept supporting files',async({page})=>{for(const route of ['order','quote']){await page.goto('/#'+route);await page.getByLabel('First Name').fill('Alex');await page.getByLabel('Surname').fill('Silva');await page.getByLabel('Contact No').fill('abc');await page.getByLabel('Email address').fill('alex@example.com');expect(await page.getByLabel('Contact No').evaluate(e=>e.checkValidity())).toBe(false);await page.getByLabel('Contact No').fill('+61 400 000 000');await page.getByLabel('Valuation Type').selectOption('Other');await expect(page.getByRole('dialog')).toBeVisible();await page.getByLabel('Other valuation requirements').fill('Portfolio assessment');await page.getByRole('button',{name:'Save requirements'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await page.getByLabel('Property type').selectOption('House');await page.getByLabel('Purpose',{exact:false}).selectOption('Portfolio review');await page.getByLabel('Property address').fill('12 Sample Street, Sydney');await page.getByLabel('Attach a file',{exact:true}).setInputFiles({name:'brief.pdf',mimeType:'application/pdf',buffer:Buffer.from('sample brief')});await expect(page.getByText('brief.pdf',{exact:true})).toBeVisible();await page.getByRole('checkbox').check();await page.locator('.order-form > form button.full').click();await expect(page.getByRole('status')).toContainText('Thank you, Alex.');await expect(page.getByRole('status')).toContainText('We will review your requirements and get in touch.');}});
test('branding, language menu and layouts work on desktop and mobile',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390]){await page.setViewportSize({width,height:900});await page.goto('/');await expect(page.locator('h1')).toContainText('Independent.');await expect(page.locator('.brand-logo')).toBeVisible();await page.locator('.brand-logo').evaluate(i=>i.decode());await page.getByRole('button',{name:'English'}).click();await expect(page.getByText('Request language assistance')).toBeVisible();await page.getByRole('button',{name:'English'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`reference/herriton-${width}.png`,fullPage:true});for(const route of ['order','quote','market']){await page.goto('/#'+route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}expect(errors).toEqual([]);});

test('failed delivery preserves entered data and never shows success',async({page})=>{
 await page.route('**/api/enquiries',route=>route.fulfill({status:502,json:{error:'Your enquiry could not be sent. Please try again later.'}}));
 await page.goto('/#contact');await page.getByLabel('First name').fill('Alex');await page.getByLabel('Last name').fill('Silva');await page.getByLabel('Email',{exact:false}).fill('alex@example.com');await page.locator('textarea').fill('Please call me about my property.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Send enquiry',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be sent');await expect(page.getByLabel('First name')).toHaveValue('Alex');await expect(page.getByRole('status')).toHaveCount(0);
});
test('unconfigured email service cannot submit or claim success',async({page})=>{
 await page.route('**/api/form-config',route=>route.fulfill({json:{available:false,siteKey:null,attachmentsEnabled:false}}));await page.goto('/#order');await expect(page.getByText('Email enquiries are not configured yet.',{exact:true})).toBeVisible();await expect(page.locator('.order-form > form button.full')).toBeDisabled();await expect(page.getByLabel('Attach a file',{exact:true})).toBeDisabled();
});
