import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {createApp,configuration} from './app.js';
const origin='https://herriton.example';
const env={NODE_ENV:'production',APP_ORIGINS:origin,SMTP_HOST:'smtp.example',SMTP_USER:'server-user',SMTP_PASS:'private-secret',MAIL_FROM:'forms@herriton.example',MAIL_TO:'lahiru.xtream@gmail.com',TURNSTILE_SITE_KEY:'public-key',TURNSTILE_SECRET_KEY:'private-captcha'};
const data={firstName:'Alex',surname:'Silva',phone:'0400000000',email:'alex@example.com',valuation:'Market Assessment',propertyType:'House',purpose:'Buying or selling',address:'12 Sample Street',consent:true,website:''};
const success=()=>Promise.resolve({accepted:[env.MAIL_TO]});
function fixture(options={}){return createApp({config:configuration(env),sendMail:success,verifyCaptcha:async()=>true,...options})}
function post(app,payload=data,kind='valuation'){return request(app).post('/api/enquiries').set('Origin',origin).set('X-Herriton-Form','1').field('kind',kind).field('payload',JSON.stringify(payload)).field('captchaToken','test-token')}
test('all form types send only to configured recipient with safe reply-to',async()=>{const messages=[];const app=fixture({sendMail:async m=>{messages.push(m);return success()}});for(const kind of ['valuation','quote','contact','location','partner']){const payload=['valuation','quote'].includes(kind)?data:{firstName:'Alex',lastName:'Silva',email:'alex@example.com',phone:'',message:'Please contact me.',consent:true,website:'',...(kind==='partner'?{business:'Sample Advisory',profession:'Other'}:{area:'Sydney'})};assert.equal((await post(app,payload,kind)).status,200);}assert.equal(messages.length,5);for(const m of messages){assert.equal(m.to,env.MAIL_TO);assert.equal(m.from.address,env.MAIL_FROM);assert.equal(m.replyTo,data.email);assert.equal(m.disableFileAccess,true);assert.equal(m.disableUrlAccess,true);assert.ok(m.text.includes('Alex'));assert.ok(m.html.includes("HERRITON"));assert.ok(m.html.includes("Alex"));}});
test('rejects spoofed origins, missing header, injected recipients, invalid fields, no consent and honeypot',async()=>{const app=fixture();assert.equal((await post(app).set('Origin','https://attacker.example')).status,403);assert.equal((await post(app).unset('X-Herriton-Form')).status,403);for(const payload of [{...data,to:'attacker@example.com'},{...data,email:'alex@example.com\r\nBcc: bad@example.com'},{...data,phone:'abc'},{...data,consent:false},{...data,website:'spam'},{...data,notes:'x'.repeat(4001)}])assert.equal((await post(app,payload)).status,400);});
test('does not show success on CAPTCHA or SMTP failure',async()=>{assert.equal((await post(fixture({verifyCaptcha:async()=>false}))).status,400);const r=await post(fixture({sendMail:async()=>{throw Object.assign(Error('private credentials'),{code:'SMTP_FAIL'})}}));assert.equal(r.status,502);assert.ok(!r.text.includes('private credentials'));assert.equal((await post(fixture({sendMail:async()=>({accepted:[]})}))).status,502);});
test('rate limits submissions',async()=>{const app=fixture({rateLimitMax:1});assert.equal((await post(app)).status,200);assert.equal((await post(app)).status,429);});
test('attachments require scanner, allowed type, genuine signature, size and scan success',async()=>{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');assert.equal((await post(fixture()).attach('attachments',png,'photo.png')).status,503);const config=configuration({...env,CLAMAV_HOST:'127.0.0.1'});const app=fixture({config,scan:async()=>{}});assert.equal((await post(app).attach('attachments',png,'photo.png')).status,200);assert.equal((await post(app).attach('attachments',Buffer.from('fake'), 'photo.png')).status,400);assert.equal((await post(app).attach('attachments',png,'bad.exe')).status,400);assert.equal((await post(app).attach('attachments',Buffer.alloc(5*1024*1024+1),'large.pdf')).status,413);assert.equal((await post(fixture({config,scan:async()=>{throw Error('malware')}})).attach('attachments',png,'photo.png')).status,422);});
test('production fails closed without secrets or HTTPS; config exposes no secrets',async()=>{assert.throws(()=>configuration({NODE_ENV:'production'}));assert.throws(()=>configuration({...env,APP_ORIGINS:'http://example.com'}));const res=await request(fixture()).get('/api/form-config');assert.equal(res.body.siteKey,'public-key');assert.ok(!res.text.includes('private-secret'));assert.ok(!res.text.includes('private-captcha'));assert.equal(res.headers['cache-control'],'no-store');assert.ok(res.headers['content-security-policy']);assert.ok(res.headers['strict-transport-security']);});
test('real CAPTCHA verification checks hostname and action and never exposes its secret',async()=>{const original=globalThis.fetch;try{for(const answer of [{success:false},{success:true,hostname:'attacker.example',action:'enquiry'},{success:true,hostname:'herriton.example',action:'other'},{success:true,hostname:'herriton.example',action:'enquiry'}]){globalThis.fetch=async(url,options)=>{assert.equal(url,'https://challenges.cloudflare.com/turnstile/v0/siteverify');assert.equal(options.body.get('secret'),env.TURNSTILE_SECRET_KEY);return {ok:true,json:async()=>answer}};const app=createApp({config:configuration(env),sendMail:success});assert.equal((await post(app)).status,answer.success&&answer.hostname==='herriton.example'&&answer.action==='enquiry'?200:400);}}finally{globalThis.fetch=original}});
test('missing SMTP configuration fails without sending and no success',async()=>{const config=configuration({APP_ORIGINS:origin});const app=createApp({config,sendMail:()=>{throw Error('Should never send')}});assert.equal((await post(app)).status,503);assert.equal((await request(app).get('/api/form-config')).body.available,false);});
