import React, { useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, MapPin, ShieldCheck, House, Building2, Users, FileText, Search, Leaf } from 'lucide-react';

export const companyLinks = [['clients','Our Clients'],['specialties','Our Specialties'],['insights','Insight'],['locations','Our Locations'],['contact','Contact Us'],['partners','Referral Partner'],['about','About Us']];
const images = {
 home:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=85',
 office:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=85',
 room:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85'
};
const headings = {
 clients:['OUR CLIENTS','Different journeys.','A shared need for clarity.','From homeowners to professional advisers, every property decision deserves a considered perspective.'],
 specialties:['OUR SPECIALTIES','The right expertise.','For your property.','Explore valuation services for homes, business premises, land and specialised property.'],
 insights:['INSIGHT','A fresh perspective','on property.','Practical reading to help you prepare, ask better questions and understand the valuation journey.'],
 locations:['OUR LOCATIONS','Local understanding.','Across Sydney and beyond.','Explore our service areas across Sydney and New South Wales. Enquire to confirm availability for your property.'],
 contact:['CONTACT US','Good conversations.','Clearer next steps.','Tell us about your property and what you have in mind. We’ll help you find a starting point.'],
 partners:['REFERRAL PARTNER','Better connections.','Considered advice.','A straightforward way for professional advisers to connect their clients with property valuation support.'],
 about:['ABOUT US','Property is personal.','So is our approach.','Our approach to property: independent perspective, local understanding and clear communication.']
};
const specialties = [
 ['Residential',House,'From family homes to investment apartments.',['Home and apartment valuations','Pre-purchase assessments','Deceased estate property','Residential rent reviews']],
 ['Commercial',Building2,'A considered view of property used for business.',['Office buildings','Commercial market assessments','Pre-purchase valuations','Commercial rental reviews']],
 ['Retail',Building2,'Understanding the spaces where businesses meet people.',['Street shops','Retail strips','Shopping centres','Retail rent reviews']],
 ['Land & development',Leaf,'Perspective on land and its possibilities.',['Vacant land','Herritonage and rural property','Subdividable land','Development sites']],
 ['Industrial',Building2,'Property insight for spaces that keep business moving.',['Warehouses','Factories','Industrial sites','Storage facilities']],
 ['Specialised property',FileText,'A tailored starting point for a more complex brief.',['Strata property','Hospitality premises','Asset portfolios','Special-purpose buildings']]
];
const regions = ['Sydney CBD','Eastern Suburbs','Inner West','North Shore','Northern Suburbs','Northern Beaches','Hills District','Western Suburbs','Canterbury Bankstown','St George','Sutherland Shire','South Eastern Sydney','Macarthur','Forest District','Central Coast'];
const articles = [
 {id:'prepare',category:'Getting started',title:'Preparing for a property valuation',image:images.home,description:'A simple checklist for a more useful first conversation.',body:[['Start with the purpose','Write down why you need the valuation and who will use the report. Sharing this at the beginning helps the valuer discuss the scope with you.'],['Gather the basics','Have the property address, property type and any available plans ready. Note recent improvements and any access arrangements that may affect an inspection.'],['Make your questions visible','Bring a list of questions about the process, timing and report. Confirm the fee and agreed scope before proceeding.']]},
 {id:'report',category:'Understanding valuations',title:'What goes into a valuation report?',image:images.room,description:'The property, the evidence and the reasoning behind the assessment.',body:[['A property in context','A report describes the property being assessed and the purpose and date of the valuation. These details give the assessment its context.'],['Evidence and explanation','The valuer considers relevant property information and market evidence, explaining the approach and assumptions used. The exact report content depends on the agreed scope.'],['Read it as a whole','The conclusion sits alongside assumptions, limitations and supporting information. Ask the valuer to explain anything that is unclear before relying on the report.']]},
 {id:'brief',category:'Getting started',title:'A clearer brief for your commercial property',image:images.office,description:'Useful information to have ready before you enquire.',body:[['Describe the property','Start with its address, current use and approximate size. Mention whether it is vacant, occupied or part of a larger holding.'],['Share available information','Existing plans, tenancy information and property documents can help frame the initial discussion. The valuer can confirm what is needed for your brief.'],['Agree the next step','Explain your intended use of the report and any deadline. Confirm the scope, access requirements and expected delivery arrangements together.']]}
];
function EnquiryForm({partner=false,region=''}){
 const [sent,setSent]=useState(false);
 if(sent)return <div className="success" role="status"><ShieldCheck size={46}/><h2>{partner?'Your introduction is ready.':'Thanks for reaching out.'}</h2><p>This is a demo confirmation. No information has been sent or saved.</p><button className="button" onClick={()=>setSent(false)}>Start another enquiry <ArrowRight size={17}/></button></div>;
 return <form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-grid"><label className="field">First name *<input required name="firstName" autoComplete="given-name"/></label><label className="field">Last name *<input required name="lastName" autoComplete="family-name"/></label></div><label className="field">Email *<input required type="email" name="email" autoComplete="email"/></label><label className="field">Phone<input type="tel" name="phone" autoComplete="tel" pattern="[+]?[0-9][0-9 ]{7,18}" title="Enter 8?19 digits, with optional spaces and a leading +."/></label>{partner?<><label className="field">Business name *<input required name="business"/></label><label className="field">Your profession<select name="profession"><option>Accountant or financial adviser</option><option>Solicitor or conveyancer</option><option>Real estate professional</option><option>Mortgage broker</option><option>Other</option></select></label></>:<label className="field">Property address or area<input name="area" defaultValue={region}/></label>}<label className="field">{partner?'Tell us about your business':'How can we help?'} *<textarea name="message" rows="4" required/></label><label className="consent"><input required type="checkbox"/>I understand this is a demo enquiry and no information will be sent.</label><button className="button full">{partner?'Register your interest':'Send sample enquiry'} <ArrowUpRight size={17}/></button><small className="demo-note">Client preview · no live submissions</small></form>;
}
function PageCTA({go}){return <section className="page-cta"><div><div className="eyebrow">YOUR NEXT CHAPTER</div><h2>Let’s find your next step.</h2><p>Start with a conversation about your property.</p></div><button className="button lime" onClick={()=>go('contact')}>Talk to us <ArrowUpRight size={18}/></button></section>}
export default function CompanyPages({page,go,order}){
 const [query,setQuery]=useState('');const [region,setRegion]=useState('');const [category,setCategory]=useState('All insights');const [article,setArticle]=useState(null);
 const [eyebrow,title,accent,description]=headings[page];
 return <main className="company-page"><section className="company-hero section"><a className="breadcrumb" href="#home" onClick={()=>go('home')}>Home <span>/</span> {companyLinks.find(([id])=>id===page)[1]}</a><div className="eyebrow">{eyebrow}</div><h1>{title}<br/><em>{accent}</em></h1><p>{description}</p><span className="hero-line"/></section>
 {page==='clients'&&<section className="section"><div className="section-heading"><div><div className="eyebrow">PEOPLE & PROFESSIONALS</div><h2>Who we’re here to help.</h2></div><p>Property advice shaped around<br/>the person behind the brief.</p></div><div className="info-grid">{[[House,'Homeowners & buyers','Clarity when you are planning a purchase, preparing to sell or looking to understand your home.'],[Building2,'Investors & businesses','A considered view of residential portfolios, commercial premises and property assets.'],[FileText,'Legal professionals','A clear starting point for property briefs, estate matters and client instructions.'],[Users,'Accountants & advisers','Valuation support shaped around the purpose and requirements of your client’s brief.']].map(([Icon,t,d])=><article className="info-card" key={t}><Icon size={29}/><h3>{t}</h3><p>{d}</p></article>)}</div><div className="editorial-split"><img src={images.room} alt="Welcoming residential living space"/><div><div className="eyebrow">RELATIONSHIPS THAT MATTER</div><h2>A good experience<br/>starts with listening.</h2><p>Every brief starts with your circumstances: the property, the decision ahead and the information you need. Our service approach keeps the scope clear and the conversation open.</p><button className="button" onClick={()=>go('partners')}>Explore referral partnerships <ArrowUpRight size={17}/></button><small className="content-note"></small></div></div></section>}
 {page==='specialties'&&<section className="section"><div className="info-grid specialties-grid">{specialties.map(([t,Icon,d,items])=><article className="info-card" key={t}><Icon size={30}/><h2>{t}</h2><p>{d}</p><ul>{items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><button className="text-button" onClick={order}>Request a valuation <ArrowUpRight size={16}/></button></article>)}</div><div className="inline-note"><ShieldCheck size={25}/><p>Not sure which service fits? Tell us your purpose and property type so the appropriate scope can be discussed.</p><button className="text-button" onClick={()=>go('contact')}>Ask a question <ArrowRight size={17}/></button></div></section>}
 {page==='insights'&&<section className="section insights-section">{article?<article className="reading-panel"><button className="text-button" onClick={()=>setArticle(null)}>← Back to all insights</button><img src={article.image} alt="Property illustration for the article"/><div className="eyebrow">{article.category} · HERRITON JOURNAL</div><h2>{article.title}</h2><p className="reading-intro">{article.description}</p>{article.body.map(([t,d])=><section key={t}><h3>{t}</h3><p>{d}</p></section>)}<small className="content-note">General information; discuss your specific requirements with your valuer.</small></article>:<><div className="filter-tabs" aria-label="Filter insights">{['All insights','Getting started','Understanding valuations'].map(t=><button aria-pressed={category===t} className={category===t?'selected':''} key={t} onClick={()=>setCategory(t)}>{t}</button>)}</div><div className="service-grid">{articles.filter(a=>category==='All insights'||a.category===category).map(a=><button className="service-card journal-card" key={a.id} onClick={()=>{setArticle(a);window.scrollTo({top:330,behavior:'smooth'})}}><div className="card-image"><img src={a.image} alt=""/><span className="round-arrow"><ArrowUpRight size={21}/></span></div><div className="eyebrow">{a.category}</div><h3>{a.title}</h3><p>{a.description}</p><span className="read-link">Read insight <ArrowRight size={15}/></span></button>)}</div></>}</section>}
 {page==='locations'&&<section className="section"><div className="locations-heading"><div><div className="eyebrow">FIND YOUR AREA</div><h2>Closer to your property.</h2></div><label className="location-search"><Search size={19}/><input aria-label="Search service areas" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search an area, e.g. Inner West" type="search"/></label></div><div className="location-grid">{regions.filter(r=>r.toLowerCase().includes(query.toLowerCase().trim())).map(r=><button key={r} aria-pressed={region===r} className={region===r?'location-card selected':'location-card'} onClick={()=>setRegion(r)}><MapPin size={21}/><span>{r}</span><ArrowUpRight size={17}/></button>)}</div>{!regions.some(r=>r.toLowerCase().includes(query.toLowerCase().trim()))&&<div className="empty-state"><h3>No matching areas.</h3><p>Try a nearby area or contact us to discuss your property.</p><button className="button secondary" onClick={()=>setQuery('')}>Show all areas</button></div>}{region&&<div className="location-detail" role="region" aria-label={`${region} enquiry`}><div><div className="eyebrow">YOUR SELECTED AREA</div><h2>{region}</h2><p>Enquire about a valuation in {region}. Share your property address and purpose to help confirm the scope and availability.</p><button className="text-button" onClick={()=>setRegion('')}>Close enquiry ×</button></div><div className="quote-panel"><h3>Ask about your area.</h3><EnquiryForm key={region} region={region}/></div></div>}<div className="inline-note"><MapPin size={24}/><p>Your area isn’t listed? We can start with your address and discuss the next step.</p><button className="text-button" onClick={()=>go('contact')}>Get in touch <ArrowRight size={17}/></button></div></section>}
 {page==='contact'&&<section className="section contact-layout"><div><div className="eyebrow">LET’S TALK PROPERTY</div><h2>A question today.<br/>A clearer path tomorrow.</h2><p>For a valuation enquiry, include the property address, your intended use of the report and any timing requirements.</p><div className="contact-method"><MapPin size={24}/><div><h3>Sydney & New South Wales</h3><p>Appointments and property access by arrangement.</p></div></div><div className="contact-method"><FileText size={24}/><div><h3>Prefer to request a report?</h3><p>Our guided form takes you through the details.</p><button className="text-button" onClick={order}>Start a valuation request <ArrowRight size={16}/></button></div></div><img className="contact-photo" src={images.home} alt="Contemporary house and garden"/></div><div className="quote-panel"><h2>Get in touch.</h2><p>A few details are all we need to start.</p><EnquiryForm/></div></section>}
 {page==='partners'&&<><section className="section contact-layout"><div><div className="eyebrow">BUILT AROUND YOUR CLIENT</div><h2>A thoughtful extension<br/>of your service.</h2><p>For solicitors, accountants, brokers and property professionals who want a clear pathway for valuation enquiries.</p>{[['01','Introduce your practice','Tell us about your business and the kinds of property briefs your clients bring to you.'],['02','Discuss the right approach','Agree how introductions, scope and communication would work.'],['03','Connect with confidence','Help your client take the next step with clear expectations.']].map(([n,t,d])=><div className="partner-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}<small className="content-note">Partnership arrangements are illustrative and would be agreed before a live referral service begins.</small></div><div className="quote-panel"><div className="eyebrow">LET’S WORK TOGETHER</div><h2>Become a referral partner.</h2><EnquiryForm partner/></div></section></>}
 {page==='about'&&<section className="section"><div className="editorial-split about-story"><img src={images.home} alt="Modern home with open garden space"/><div><div className="eyebrow">THE HERRITON PERSPECTIVE</div><h2>More understanding.<br/>Better conversations.</h2><p>A property can be a home, a business or the start of a new chapter. Understanding its value begins with understanding what matters to you.</p><p>Our service approach is simple: make the process approachable, explain the evidence clearly and keep the client informed.</p><button className="button" onClick={()=>go('contact')}>Start a conversation <ArrowUpRight size={17}/></button></div></div><div className="section-heading"><div><div className="eyebrow">WHAT GUIDES US</div><h2>Our principles, in practice.</h2></div></div><div className="info-grid values-grid">{[[ShieldCheck,'Independent thinking','A considered view of the property and the evidence, with the purpose of the brief kept in focus.'],[MapPin,'Local perspective','An interest in the neighbourhood, the property’s character and the context around it.'],[Users,'Human communication','Straightforward explanations, useful questions and a clear view of the next step.']].map(([Icon,t,d])=><article className="info-card" key={t}><Icon size={29}/><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
 <PageCTA go={go}/></main>;
}
