import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ShieldCheck, Upload, X } from 'lucide-react';
export const valuationTypes = ['Market Assessment','Capital Gains','SMSF Valuation','Retrospective Capital Gains','Retrospective','Stamp Duty','Rent Review','Other'];
export default function RequestForm({quote=false}) {
 const [data,setData]=useState({valuation:'Market Assessment',propertyType:'',purpose:''}); const [files,setFiles]=useState([]); const [done,setDone]=useState(false); const [error,setError]=useState(''); const [popup,setPopup]=useState(false); const dialog=useRef(null); const other=useRef(null);
 useEffect(()=>{if(popup){dialog.current.showModal();}else if(dialog.current?.open){dialog.current.close();other.current?.focus();}},[popup]);
 const update=(name,value)=>setData(d=>({...d,[name]:value}));
 const field=(name,label,type='text',required=true)=><label className="field">{label}{required?' *':''}<input name={name} type={type} required={required} value={data[name]||''} autoComplete={{firstName:'given-name',surname:'family-name',email:'email',phone:'tel',address:'street-address'}[name]} pattern={type==='tel'?'[+]?[0-9][0-9 ]{7,18}':undefined} title={type==='tel'?'Enter a valid contact number (8–20 characters).':undefined} onChange={e=>update(name,e.target.value)}/></label>;
 if(done)return <div className="success" role="status"><ShieldCheck size={48}/><div className="eyebrow">{quote?'QUOTE PREVIEW COMPLETE':'VALUATION PREVIEW COMPLETE'}</div><h2>Thank you, {data.firstName}.</h2><p>Your {quote?'free quote':'valuation'} request for <strong>{data.address}</strong> is ready.</p><p>This is a demo confirmation. No information or files have been sent.</p><button className="button" onClick={()=>setDone(false)}>Review your details <ArrowRight size={17}/></button></div>;
 return <><form onSubmit={e=>{e.preventDefault();if(data.valuation==='Other'&&!data.otherPurpose?.trim()){setPopup(true);return;}setDone(true)}}>
 <div className="form-section-title"><span>01</span><h3>Your contact information</h3></div><div className="form-grid">{field('firstName','First Name')}{field('surname','Surname')}{field('phone','Contact No','tel')}{field('email','Email address','email')}</div>
 <div className="form-section-title"><span>02</span><h3>Your service information</h3></div>
 <label className="field">Valuation Type *<select required value={data.valuation} onChange={e=>{update('valuation',e.target.value);if(e.target.value==='Other')setPopup(true)}}>{valuationTypes.map(t=><option key={t}>{t}</option>)}</select></label>
 {data.valuation==='Other'&&<div className="other-purpose"><span>{data.otherPurpose||'Please specify your valuation requirements.'}</span><button ref={other} type="button" className="text-button" onClick={()=>setPopup(true)}>Edit requirements</button></div>}
 <div className="form-grid"><label className="field">Property type *<select required value={data.propertyType} onChange={e=>update('propertyType',e.target.value)}><option value="">Select property type</option>{['House','Apartment','Townhouse','Commercial','Retail','Industrial','Vacant land','Rural','Other'].map(t=><option key={t}>{t}</option>)}</select></label><label className="field">Purpose *<select required value={data.purpose} onChange={e=>update('purpose',e.target.value)}><option value="">Select purpose</option>{['Buying or selling','Tax reporting','Estate planning','Family settlement','Portfolio review','Rental assessment','Other'].map(t=><option key={t}>{t}</option>)}</select></label></div>
 {field('address','Property address')}<label className="field">Additional information<textarea rows="4" value={data.notes||''} onChange={e=>update('notes',e.target.value)} placeholder="Tell us about your property, preferred timing or any special requirements."/></label>
 <label className="field upload-label"><Upload size={20}/><span>Attach a file</span><small>PDF, DOC, DOCX, JPG or PNG · up to 10 MB per file</small><input aria-label="Attach a file" type="file" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>{const next=Array.from(e.target.files);if(next.some(f=>f.size>10*1024*1024)){setError('Each attachment must be 10 MB or smaller.');e.target.value='';setFiles([]);}else{setError('');setFiles(next);}}}/></label>{error&&<p role="alert" className="file-error">{error}</p>}{files.length>0&&<ul className="file-list">{files.map((f,i)=><li key={i}><Check size={14}/>{f.name}</li>)}</ul>}
 <label className="consent"><input type="checkbox" required/>I understand this is a preview and my details and attachments will not be sent.</label><button disabled={!!error} className="button full">{quote?'Order a Free quote':'Request a valuation'} <ArrowRight size={18}/></button><small className="demo-note">Preview only. No payment or live submission.</small>
 </form><dialog ref={dialog} className="purpose-dialog" onCancel={()=>setPopup(false)} onClick={e=>{if(e.target===dialog.current)setPopup(false)}}><div className="dialog-heading"><h2>A little more detail.</h2><button type="button" aria-label="Close requirements" onClick={()=>setPopup(false)}><X/></button></div><p>Tell us what you need the valuation for so the right scope can be discussed.</p><form onSubmit={e=>{e.preventDefault();setPopup(false)}}><label className="field">Other valuation requirements *<textarea autoFocus required rows="4" value={data.otherPurpose||''} onChange={e=>update('otherPurpose',e.target.value)}/></label><button className="button full">Save requirements <Check size={17}/></button></form></dialog></>;
}
