import React,{useEffect,useRef,useState} from 'react';
export function useSubmission(){
 const [config,setConfig]=useState(null),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reset,setReset]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/form-config',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setConfig).catch(e=>{if(e.name!=='AbortError')setError('Enquiries are unavailable at the moment. Please try again later.');});return()=>controller.abort()},[]);
 async function submit(kind,payload,files=[]){if(busy)return false;setError('');if(!config?.available){setError('Email enquiries are not configured yet. Please try again later.');return false}if(config.siteKey&&!token){setError('Please complete the security verification.');return false}setBusy(true);try{const body=new FormData();body.append('kind',kind);body.append('payload',JSON.stringify(payload));body.append('captchaToken',token);files.forEach(f=>body.append('attachments',f));const response=await fetch('/api/enquiries',{method:'POST',headers:{'X-Herriton-Form':'1'},body,signal:AbortSignal.timeout(60000)});const result=await response.json();if(!response.ok||result.ok!==true)throw Error(result.error||'Your enquiry could not be sent.');return true}catch(e){setError(e.name==='TimeoutError'?'The request timed out. Please contact us before retrying to avoid a duplicate enquiry.':e.message||'Your enquiry could not be sent. Please try again later.');return false}finally{setBusy(false);setToken('');setReset(v=>v+1)}}
 return {config,token,setToken,busy,error,reset,submit};
}
let scriptPromise;
function loadTurnstile(){if(window.turnstile)return Promise.resolve(window.turnstile);if(!scriptPromise)scriptPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=()=>resolve(window.turnstile);script.onerror=()=>{scriptPromise=null;reject(Error('Security verification could not load.'))};document.head.append(script)});return scriptPromise}
export function SubmissionSecurity({submission}){const container=useRef(null),[failed,setFailed]=useState(false);const {config,setToken,reset,error}=submission;
 useEffect(()=>{if(!config?.siteKey)return;let active=true,id,api;setFailed(false);loadTurnstile().then(t=>{if(!active)return;api=t;id=t.render(container.current,{sitekey:config.siteKey,action:'enquiry',size:'flexible',callback:setToken,'expired-callback':()=>setToken(''),'error-callback':()=>{setToken('');setFailed(true)}})}).catch(()=>setFailed(true));return()=>{active=false;if(api&&id!==undefined)api.remove(id)}},[config?.siteKey,reset,setToken]);
 return <><div className="spam-trap" aria-hidden="true"><label>Leave this field empty<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{config?.siteKey&&<div ref={container} className="security-widget"/>}{failed&&<p role="alert" className="file-error">Security verification could not load. Please refresh and try again.</p>}{error&&<p role="alert" className="file-error">{error}</p>}{config&&!config.available&&<p className="demo-note">Email enquiries are not configured yet.</p>}</>;
}
